### ISSUE TITLE
Failback to smaller size

### ISSUE THREAD

**Issue by olsh** [mat/besticon#11]
It would be nice to have an option to failback to a smaller size if there is no an icon with desired size.

For instance I want to get and icon:
https://icons.better-idea.org/icon?url=asp.net&size=128

But it returns a generated icon, but I would like to get this one, despite it's smaller than 128px
https://www-asp.azureedge.net/v-2016-10-05-010/images/content/favicon.ico

**Comment by mat** [comment]
This sounds a lot like https://github.com/mat/besticon/issues/7 to me, don't you think?

**Comment by olsh** [comment]
Oops, sorry! Didn't notice this.
