### ISSUE TITLE
Grey icons: Extract fallback colors from .ico images, too

### ISSUE THREAD

**Issue by mmkal** [mat/besticon#12]
A lot of sites seem to have grey as the background colour for their letter icon. I'm not sure why this is as poking through the code, and looking at some examples, it looks like it attempts to pick up the main colour in smaller icons to create the letter one. 

Example: https://icons.better-idea.org/icons?url=twitter.com#result
The letter icon should really be light blue to match the Twitter bird. 

Example that works: https://icons.better-idea.org/icons?url=facebook.com#result
This one's letter icon is Facebook-blue as expected.

**Comment by mat** [comment]
The reason is simple, unfortunately: The ico package I wrote is very simple as it can only extract metadata like dimensions for `.ico` files but it can't decode the real image data.

That's why color extraction works only for cases where there is at least one non .ico file present, like in your examples.

See my comment here at https://github.com/mat/besticon/issues/8#issuecomment-250001338. In other words I'd love to have it, PRs welcome ;)

I am leaving this issue open so there's this missing feature is documented at least.

**Comment by mmkal** [comment]
Got it. I've actually just submitted [a pull request](https://github.com/mat/besticon/pull/14) that's related to this... but doesn't exactly fix this issue, only mitigates it. I'm not familiar with Go, so extracting image data from a .ico when Go doesn't natively support it seemed a little ambitious.

The change in the pull request just adds an optional query flag that allows requesting an arbitrarily coloured icon rather than a grey one. The colour is based on the hash of the url passed so it will always be the same for any given url. So twitter won't be Twitter-blue, but in my case - where I am hoping to use the service for a lot of images on a single page - it will at least help avoid seeing a sea of grey. 

I didn't link to this issue in the pull request as it's only indirectly related. But just thought I'd leave give some context for creating it.

**Comment by mmkal** [comment]
Incidentally, I just tried changing the user agent from to `User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36` and a bunch of apple touch icons started getting picked up as a result.

From debugging the twitter.com case, it looks like with the existing user agent (`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10`), the mobile twitter site is fetched. Then all the pngs seem to 404. Changing it to the above yields this:
![twitter](https://abs.twimg.com/icons/apple-touch-icon-192x192.png)
instead of this:
![twitter](https://icons.better-idea.org/icon?url=twitter.com&size=192)

Could be worth looking into. I'd be happy to submit another pull request, or add this change to https://github.com/mat/besticon/pull/14 

Let me know what you think.

**Comment by mat** [comment]
Thank you @mmkal, the User Agent things was a good catch, never though about trying that out!

**Comment by mat** [comment]
Closing this to keep the bug tracker tidy with things I can realistically work on in the near future. I'm listing this as a known bug at #16.
