### ISSUE TITLE
Question - are tests running against local code, or github repo?

### ISSUE THREAD

**Issue by mmkal** [mat/besticon#15]
Hi - I noticed that when running locally, that I could add a failing test to (for example), [./besticon/iconserver/server_test.go](https://github.com/mat/besticon/blob/master/besticon/iconserver/server_test.go), run `go test ./besticon/iconserver`, and the command prompt would correctly tell me a test had failed. But if I ran `make test` or `make test_all` (i.e. ran all tests) then it would tell me all tests passed. 

Was I doing something wrong here? It looks to me like the [Makefile](https://github.com/mat/besticon/blob/master/Makefile) is testing the code in the github repo, rather than the code as it is on the machine. If so, maybe the lines referencing the repo should be changed to filesystem references. e.g. from `go test -v github.com/mat/besticon/lettericon` to `go test -v ./besticon/lettericon`. Or did I set something up wrong?

**Comment by mat** [comment]
I've got to say _can't reproduce_, unfortunately. When I break a test in `server_test.go` and run `make test_all` I get (abbreviated):

```
go get github.com/mat/besticon/...
go test -v github.com/mat/besticon/ico
=== RUN   TestParseICO
--- PASS: TestParseICO (0.00s)
.
.
.
go test -v github.com/mat/besticon/besticon/iconserver
=== RUN   TestGetIndex
--- PASS: TestGetIndex (0.00s)
=== RUN   TestGetIcons
--- FAIL: TestGetIcons (1.06s)
	server_test.go:229: 	Expected 'text/html; charset=utf-8' to be 'text/html; charset=utf-'
		
=== RUN   TestGetIcon
--- PASS: TestGetIcon (0.00s)
=== RUN   TestGetIconWithFallBackURL
--- PASS: TestGetIconWithFallBackURL (0.00s)
=== RUN   TestGetIconWith404Page
--- PASS: TestGetIconWith404Page (0.00s)
=== RUN   TestGet404IconWithFallbackColor
--- PASS: TestGet404IconWithFallbackColor (0.00s)
=== RUN   TestGet404IconWithInvalidFallbackColor
--- PASS: TestGet404IconWithInvalidFallbackColor (0.00s)
=== RUN   TestGetAllIcons
--- PASS: TestGetAllIcons (0.00s)
=== RUN   TestGetPopular
--- PASS: TestGetPopular (0.00s)
=== RUN   TestGetLetterIcon
--- PASS: TestGetLetterIcon (0.01s)
=== RUN   TestGetObsoleteApiRedirect
--- PASS: TestGetObsoleteApiRedirect (0.00s)
=== RUN   TestGet404
--- PASS: TestGet404 (0.00s)
FAIL
exit status 1
FAIL	github.com/mat/besticon/besticon/iconserver	1.096s
make: *** [test_all] Error 1
```

So in other words (and as far as my knowledge about go as a hobbyist goes ;)) it definitely uses the local code in the `$GOPATH` first.
