### ISSUE TITLE
Web service down?

### ISSUE THREAD

**Issue by dbrowder** [mat/besticon#17]
I've been playing around with the web service for the past week in my app and noticed it went down last night throwing a 502 error. 

Was this shut off because of my testing or is there some other issue?  I will look into self-hosting but haven't done that while developing.

**Comment by dbrowder** [comment]
The service came back up this morning, but I guess my question now is how many requests would be too many to use the free service?  I don't want to abuse it, and will set up self-hosting if I have to, but my project is pretty small.

**Comment by mat** [comment]
Hey @dbrowder, thanks for letting me know. To be honest, the service has usually been pretty stable and I don't know what happened here, but I doubt it's got something to do with you particular workload - there are lot's of other active users at this point.

Let me know if you need to know more about self hosting https://github.com/mat/besticon/blob/master/Readme.markdown#self-hosting
