### ISSUE TITLE
Request multiple sites in one query. 

### ISSUE THREAD

**Issue by dbrowder** [mat/besticon#19]
I would love to be able to request multiple sites from the JSON API and get one response with all the favicon data

**Comment by mat** [comment]
Thanks for your request, but I am afraid this is not something I am considering at this point. This would make both clients and server more complicated for no real benefits:

If you believe this could lead to better performance/throughput then I can tell you that the service is deployed using http/2 which is quite effective at pipelining. So you could say you get batching for free :-)
