### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by creichert** [mat/besticon#20]
https://icons.better-idea.org/

> 502 Bad Gateway
>
> nginx

---

Thanks again for this awesome service. Let me know if there is any way I can help out.

**Comment by creichert** [comment]
Looks like this is no longer an issue. thanks!

**Comment by mat** [comment]
Thanks for letting me know @creichert - you were quicker than my monitoring and my time to react during vacation here ;-)

By the way, self hosting is really super easy if that's something you're interested in: https://github.com/mat/besticon#self-hosting
