### ISSUE TITLE
add bigger size of icons manually

### ISSUE THREAD

**Issue by erdinc** [mat/besticon#21]
I need a feature to get higher(ex: 1024 px) resolution of original ico files. How can I add those files statically to cache or somewhere else so that I can get proper images? I want to add bigger icons of popular sites like facebook, google etc..

**Comment by mat** [comment]
Not many sites provide icons that large.

The fallback/lettericon size is currently limited to 256 for various reasons.

If you're thinking of using other icons from a different source there is also the `fallback_icon_url` parameter that could be helpful.

Does that help?
