### ISSUE TITLE
Idea: Use link rel="image_src" for YouTube channels

### ISSUE THREAD

**Issue by Jacketbg** [mat/besticon#24]
Here's an idea. YouTube channels has a reference to the generic favicon, but they also use a custom `image_src` icon link to the channel thumbnail. Example: https://www.youtube.com/user/ChainsmokersVEVO.

`<link rel="image_src" href="https://yt3.ggpht.com/-ZSYXXhPY5Zk/AAAAAAAAAAI/AAAAAAAAAAA/K_F28VrzPXQ/s900-c-k-no-mo-rj-c0xffffff/photo.jpg">`

Do you think it could be possible to add an exception for YouTube channels. I'm not sure if this is plausible though, because they are not in the form of subdomain, but a different path on the same master domain.

**Comment by mat** [comment]
I can see your point, but adding custom code for certain sites is not a thing I want to do at this point.

That said I will label this one _idea_, maybe a pattern emerges where we see that we want to have special for more sites. If that's the case I will try to come up with something...
