### ISSUE TITLE
Returning incorrect icon size

### ISSUE THREAD

**Issue by kspearrin** [mat/besticon#28]
https://icons.better-idea.org/icon?url=random.org&size=16..32..64

I would expect to get the 16x16 favicon returned. Instead I am returned a 196x196 icon which is above my max size of 64.

https://icons.better-idea.org/icons?url=random.org#result

**Comment by mat** [comment]
Hi @kspearrin, thanks for the bug report! I just wanted to say it'll be a while til I have a chance to take look as my `family_size` increased by 1 very recently and thus I have to take care of other stuff first... ;-)

**Comment by kspearrin** [comment]
No worries. I'm not a go developer or otherwise I'd love to dig into it myself.

**Comment by kspearrin** [comment]
Well, I became a go developer tonight. Check out #30  😆
