### ISSUE TITLE
CORS issue in Firefox when trying to fetch favicons using js

### ISSUE THREAD

**Issue by odebroqueville** [mat/besticon#31]
This is the error msg I'm getting: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://icons.better-idea.org/icon?url=www.ecosia.org&size=24..32..64. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)."

Which leads me to the following question: have you set the response header ‘Access-Control-Allow-Origin’ to "*"? to allow for widespread use?

(I'd very much like to use your API from my Context Search Firefox extension)

**Comment by mat** [comment]
For which resources/URLs does the header `Access-Control-Allow-Origin: *`need to be set?

**Comment by mat** [comment]
As far as I can see, setting this header on any/all of the services endpoints won't be of any effect - as long as the target images we're redirecting to (like the link above) on the third party sites have this header set correctly.

Good idea, but currently not possible I am afraid.

**Comment by odebroqueville** [comment]
Hi Mat, I'm sorry for not answering earlier, but the truth is that I don't know what the answer to your question is! I'm using your API from within a firefox web extension, so it's not being used from a website or web app. Currently, I'm using a proxy url to avoid CORS issues, but some users have expressed concern about this method. That's why I was hoping you'd be able to help me! We now have a little over 4'000 users. In the past two weeks, we acquired some 2'000 new users. I can't explain the sudden growth in users, but you may have noticed an increase in the number of requests made to your API. I don't know where you're hosting your API or what your costs are and I understand that the rate limit has been set to limit your costs. I would be happy to contribute a third (we are 2 developers working on the extension) of the donations received for the web extension, but so far we've only received the ridiculous amount of $2.50, which really doesn't cover the time spent developing the extension. Unfortunately, your API still produces somewhat unsatisfactory results: some of the icons that were working fine have been replaced by letter icons (e.g. twitter is one of them). I understand this has to do with your rate limitations, but I don't find that it's a good solution to continuously have to report the non-working favicons here so that you may then add them to HOST_ONLY_DOMAINS. I understand how the HOST_ONLY_DOMAINS works, but the only solution I can think of is for your API to store/cache the favicons (e.g. on AWS S3 or something equivalent). It would reduce the number of requests your API has to make to get the favicons and increase the amount of cloud storage used by very acceptable amount (as favicons take up very little memory). I don't know if you have the time to implement this feature. Unfortunately, my co-developer and myself don't have a clue about Go! Please let me have your thoughts on this issue.

**Comment by odebroqueville** [comment]
Not very nice of you not to answer after such a long period!
