### ISSUE TITLE
Quora.com icon not found!

### ISSUE THREAD

**Issue by odebroqueville** [mat/besticon#34]
The 32x32 icon exists and can be found at [https://qsf.ec.quoracdn.net/-3-images.favicon.ico-26-3f34badcb59c8f6c.ico](url)

The <head> section contains the following <link> element:
`<link rel="icon" href="https://qsf.ec.quoracdn.net/-3-images.favicon.ico-26-3f34badcb59c8f6c.ico">`

Please don't hesitate looking at the code in my getFaviconUrl project here:
[https://github.com/odebroqueville/getFaviconUrl/blob/master/index.js](url)

I basically look for a rel within a link that contains the word "icon":
``` 
$("link").each(function(i, element) {
        console.log(element);
        var rel = $(element).attr("rel");
        if (rel !== undefined && rel.indexOf("icon") > -1) {
          faviconUrl = $(element).attr("href");
          return false;
        }
});
```

**Comment by mat** [comment]
Thanks for your report!

I am afraid this one is also because of rate limiting. I've added `quora.com` to the HOST_ONLY_DOMAINS, which means it should start working again in a couple of days hopefully.

**Comment by odebroqueville** [comment]
What do you mean by rate limiting? Where is the limitation coming from?
