### ISSUE TITLE
More missing icons despite using main domain name

### ISSUE THREAD

**Issue by odebroqueville** [mat/besticon#35]
I'm using the following js code that uses your API:

<pre>
let url = "https://www.example.com/some/page.html";
let urlParts = url.replace('http://','').replace('https://','').split(/\//);
let domain = urlParts[0];
let faviconUrl = "https://icons.better-idea.org/icon?url=" + domain + "&size=24..32..64";
</pre>

I'm therefore stripping off url to include just the main domain name when calling your API.

Despite this, the following sites are getting letter icons instead of their available favicons. In some cases, I've noticed that the link in the href is missing the "https" part and starts with "//...". I don't know if that could be an issue in your go code:

- [x] dogpile: href="http://cdn3.inspsearchapi.com/dogpile/11.2.0.421/favicon.ico",
- [x] eBay: href="https://pages.ebay.com/favicon.ico",
- [x] Google Maps (maps.google.com):   href="//www.google.com/images/branding/product/ico/maps_32dp.ico",
- [x] Lilo (search.lilo.org): href="//www.lilosearch.org/img/newlogo/lilo16.png",
- [x] Twitter: href="//abs.twimg.com/favicons/favicon.ico"

**Comment by mat** [comment]
All working for me now, looks like they've been solved by https://github.com/mat/besticon/commit/57c4adcf7d41de26f4ce433b6d1b7b263de10a81, too.

**Comment by odebroqueville** [comment]
Dear Mat, I'm sorry to bother you with this, but Ask.com, Dogpile, eBay, Google Scholar (besticon used to produce a really nice icon for Google Scholar), Lilo and Twitter are still producing letter icons. Only Google Maps has been fixed.
![screenshot 2017-11-25 at 13 02 45 pm](https://user-images.githubusercontent.com/4818315/33230332-a939ce52-d1e1-11e7-935c-0aebf2690030.jpg)
