### ISSUE TITLE
504 Gateway Time-out when using subdomain

### ISSUE THREAD

**Issue by creichert** [mat/besticon#5]
I happened  to hit an unexpected HTTP 504 gateway when calling subdomains on `firebaseio.com`.

You can reproduce w/ a simple curl request:

```
$ curl -I 'https://icons.better-idea.org/icon?url=hacker-news.firebaseio.com&size=32' 
HTTP/2.0 504
server:nginx
date:Sat, 18 Jun 2016 21:44:52 GMT
content-type:text/html
content-length:176
```

I also get the same issue from a browser:

![img4](https://cloud.githubusercontent.com/assets/526560/16173862/36a73c04-3574-11e6-96ee-4d397881a92c.jpg)

I haven't had a chance to investigate the code but using subdomains on other apex urls seems to work just fine.

**Comment by mat** [comment]
Thank you @creichert for reporting this
