### ISSUE TITLE
Fallback to smaller size

### ISSUE THREAD

**Issue by mortenmoulder** [mat/besticon#7]
It would be extremely nice, if you could create a "`fallback_size`" (or something similar). Look at this scenario:

A) A site has a 16px and a 32px icon. If I put in `size=64` it generates an image with a background instead.
B) A site has a 32px and a 64px icon. If I put in `size=16` it grabs the next icon (because 16px doesn't exist, it picks the 32px one)

What would be extremely nice, would be a parameter that allows you to set a size, so no-matter-what it always grabs an icon, if there is an icon. If I put in `fallback_size=64` on the first scenario, it should grab the 32px icon.

Additionally: A "grab largest/smallest" would also be cool. This would allow us to use the image just with `<img src="...." />` instead of grabbing the API, going through the JSON and doing it all by ourselves.

I'm sure this could be useful to many people.

Thanks

**Comment by mat** [comment]
Hi Morten, thanks for your request. I will try to incorporate your idea in a next version of the API.

**Comment by mat** [comment]
Finally I had time to come up with something

- https://github.com/mat/besticon/compare/sizerange?expand=1
- https://iconserver.herokuapp.com 

Let me know what you guys think, @mortenmoulder, @olsh.

**Comment by mortenmoulder** [comment]
@mat Awesome! Very cool.

How exactly would this work, you say? Assuming the site only has 16px and 32px icons, but I want 64px, how would this work out?

**Comment by mat** [comment]
If 64px are perfect for your case but you would also tolerate a 16px icon you could say `16..64..200`. In your example, this would then return the 32px icon.

(I decided to always require (min, perfect, max) - users should not have a hard time to make up there mind about what numbers makes sense for their particular use case. And being so 'strict' gives more safety/flexibility for future changes.)

**Comment by olsh** [comment]
@mat , great! That's even better than my suggestion.
Thank you!

**Comment by mortenmoulder** [comment]
@mat Oh okay, cool! So if I do `32..64..200` it would grab the 64px one if there is one, otherwise it would grab the 32px one, as long as 32px is the highest value under 200. Did I get that right?

**Comment by mat** [comment]
It's really very easy, this is what's happening

1. Search the range `perfect..max` for an icon which is `perfect <= size(icon) <= max`
2. Search the range `perfect..min` for an icon which is `min <= size(icon) <= perfect` 
3. Generate a fallback icon of size `perfect` else.

In the Readme I tried to explain it like this

> Desired size range (min..perfect..max) If no image of size perfect..max nor perfect..min can be found a fallback icon will be generated.

**Comment by mortenmoulder** [comment]
@mat Yeah exactly :) Good job! 👍

**Comment by mat** [comment]
Thank you guys for your input and feedback.
